### ISSUE TITLE
META file/project has no License

### ISSUE THREAD

**Issue by samcv** [supernovus/perl6-datetime-math#10]
META file has no license, you can remedy this by:

Using a license field listed in my META file that is one of the standardized list here: https://spdx.org/licenses

If you want to choose one without a standardized name, make sure you have a license URL listed under support as well[See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).

If you purposefully want to have no license, please use 'NONE' for the license name, though that is not recommended.

**Comment by supernovus** [comment]
I will update this shortly. All of my public libraries are published under the Artistic License 2.0

**Comment by samcv** [comment]
Thank you :)
